version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3000}
      PG_HOST: db
      PG_PORT: 5432
      PG_DATABASE: ${PG_DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PGSSL: "false"
      JWT_SECRET: ${JWT_SECRET}
      BOT_TOKEN: ${BOT_TOKEN}
      ALLOW_DEV_INITDATA: "false"
      INITDATA_TTL_SECONDS: ${INITDATA_TTL_SECONDS:-86400}
      CORS_ORIGINS: ${CORS_ORIGINS:-https://orbitsend.ru}
      SKIP_DB: "false"
    ports:
      - "3000:3000"

volumes:
  pgdata:
